### PR TITLE
[nuxt-shopify-accounts] If customer email is unset, redirect to non-Multipass checkout URL

### PR DESCRIPTION
**Pull request by NWRichmond**
### WHY are these changes introduced?

Fixes [DD-186](https://nacelle.atlassian.net/browse/DD-186)

> Fix missing check for customer data in checkoutRedirect action (multipass)

Fixes [DD-123](https://nacelle.atlassian.net/browse/DD-123)

> Remove multipass secret from Nuxt env in README

### WHAT is this pull request doing?

- In `store/checkout.js`, if `rootState.account.customer.email` does not exist, redirect to regular checkout URL, rather than Multipass URL
- In `store/account.js`, don't allow the Multipass endpoint to be hit if `state.customer.email` is unset
- Linting & formatting

#### Demonstration

Unauthenticated checkout:

https://user-images.githubusercontent.com/5732000/114087730-3a869100-9882-11eb-9dcf-a33ef263b24d.mov

Authenticated checkout:

https://user-images.githubusercontent.com/5732000/114087680-2a6eb180-9882-11eb-96af-f395afaec42e.mov

## 

### How to Test

- visit https://nuxt-shopify-c-git-dd-186-fix-missing-check-for-customer-24f096.vercel.app
- perform checkout without logging in
- create an account / login with an existing account
- perform a checkout while logged in

### CODE REVIEW

**Comment by levimichael** [comment]
Screen Shot 2021-04-08 at 2 45 50 PM
@NWRichmond  I get this error while trying to log in

**Comment by NWRichmond** [comment]
@levimichael I think the issue is separate from this PR, and warrants a new bug ticket.

**Comment by NWRichmond** [comment]
@levimichael your screenshot indicates that the Deploy Preview is missing the `MYSHOPIFY_DOMAIN` which is used in the GraphQL endpoint. That's strange, because it's present in `https://vercel.com/nacelle/nuxt-shopify-customer-accounts/settings/environment-variables`:

Screen Shot 2021-04-14 at 11 50 14 AM

Screen Shot 2021-04-14 at 11 49 57 AM

I'll look into where the disconnect is...

**Comment by NWRichmond** [comment]
@levimichael when you have a moment, could you please retry the account registration process on `https://nuxt-shopify-c-git-dd-186-fix-missing-check-for-customer-24f096.vercel.app/`? It just worked for me, after updating the app to use the `publicRuntimeConfig` instead of `process.env`.

**Comment by levimichael** [comment]
Nice work!

**Pull request merged**
