### PR TITLE
Fix province & country fetch for nuxt account

### PR DESCRIPTION
**Pull request by KrisQ**
### WHY are these changes introduced?

Fixes [[DD-126](https://nacelle.atlassian.net/browse/DD-126)] 

### WHAT is this pull request doing?

The request to country and province fetch were flawed and the body didn't match what the request was asking for in each case, this fixes that

## 

### How to Test

🖥 [Local development instructions](#link-to-repo-readme)
🗒 [General testing guidelines](#link-to-testing-guidelines)
📄 [Changelog guidelines](#link-to-changelog-guidelines)

### Testing checklist

* [ ] Tested on mobile
* [ ] Tested on multiple browsers
* [ ] Tested for accessibility
* [ ] Updated the `README.md` with documentation changes
* [ ] Updated public facing documentation

### CODE REVIEW

**Comment by levimichael** [comment]
@KrisQ it looks like the preview failed to build, is there a missing dependency?

**Comment by KrisQ** [comment]
> @KrisQ it looks like the preview failed to build, is there a missing dependency?

Hey @levimichael , it looks like this is a reoccurring error lately:

image

All these fail for the same reason.

I will make a ticket for it, high priority?

**Comment by levimichael** [comment]
Yeah, we added a requirement for a NACELLE_ENDPOINT field

**Comment by levimichael** [comment]
yeah @KrisQ it needs the NACELLE_ENDPOINT variable

**Comment by KrisQ** [comment]
> yeah @KrisQ it needs the NACELLE_ENDPOINT variable

@levimichael , I added it and it looks like it was hardcoded too, but that didn't fix it :/

**Review by alexcasche — APPROVED** [review]
looks good Kristinen

**Comment by alexcasche** [comment]
The build logs indicate that `axios` is being referenced but does not exist.  `Module not found: Error: Can't resolve 'axios' in 'components/account'`.  Maybe this should be a different ticket since it is unrelated?

**Comment by alexcasche** [comment]
Closing this out and have moved the build issue to new ticket here: https://nacelle.atlassian.net/browse/DD-406

**Pull request merged**
